### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by geggleto** [binarygenius/phpthewrongway#10]
I really hope php developers don't offhandedly dismiss your write-up because I have found it very valid.

I would purpose adding some guiding questions to each of your segment's to support the conclusion you draw.

Here's a few things that I think highlight your point which I end up having to do on a daily basis.

Always use a framework
- Would you use a framework to create cron scripts?
- Would you use a framework to display a 5 page website?

Always use a design pattern
- Would you write a collection object for a simple integer array?

Always use object-oriented Programming
-  Would you write a collection of classes for doing a simple database modification script?

**Comment by lianglee** [comment]
Here what i think:

**Would you use a framework to create cron scripts?**
The cron scripts hmm...  If its make simple modification to database you don't need a frameworks,

**Would you use a framework to display a 5 page website?**

Framework is not required for such a stuff and its wastage of time.

**Would you write a collection of classes for doing a simple database modification script?**
I think, there is no need to write collection of classes for simple database modification.

**Comment by unixdigest** [comment]
@geggleto thanks for your comment, greatly appreciated.

I'm pretty sure someone would actually go as far as use a framework in order to print "Hello world" ;)

Jokes aside, I hope people get the ideas expressed without the need for further examples.
