### ISSUE TITLE
PSR-0 autoload usage is unclear

### ISSUE THREAD

**Issue by mablae** [binarygenius/phpthewrongway#22]
> If you choose to adopt the standards developed by the PHP-FIG, you have to understand that some of these standards - such as the autoloader standards PSR-0 and PSR-4 and several other standards - has a direct effect upon how you code your software.
> 
> Many industries demand highly scalable, run-time critical, and cost effective software that simply cannot be developed using these standards of the PHP-FIG.
> 
> The wrong way: Following the PHP-FIG beyond the PSR-1 and PSR-2. Thumbs down

I think the introduction of of an standard for easy autoloading with composer was the biggest revolution in the userland of PHP community at all. 

Why the hell should this `PSR-0` or `PSR-4` autoloading stuff not be used? Even when implementing an own autoloader the standard just makes it more easy to integrate. 

Namespacing is a native PHP feature, so should be some mapping to filesystem. PHP lacks that. Having a standard in userland like PSR-0 closes this lack of feature of the language. What is wrong with that?

**Comment by AlexNodex** [comment]
Because it should not period

**Comment by unixdigest** [comment]
You can find some great articles and blog posts about why this is really bad and how to deal with the issue in better ways.

**Comment by bwoebi** [comment]
A lot of the points in that article are invalidated though by the way composer handles it today. PSR-4 has less restrictions on the namespace and path, composer allows for static files to be specified (also secondary autoloaders).

PHP 5.2 compat is no longer a thing (well if it is, then uh … I give up …)

I agree on PSR-0 largely, but this doesn't reflect very well the current state of PSR-4.
I'd be interested in hearing the actual _problems_ with this one.

**Comment by Potherca** [comment]
> You can find some great articles and blog posts about why this is really bad and how to deal with the issue in better ways.

Cool. Is there a list of this somewhere?
