### ISSUE TITLE
Seems to be invalid terminology

### ISSUE THREAD

**Issue by SmiSoft** [binarygenius/phpthewrongway#25]
> but were renamed “attributes”

A data inside objects usually named "fileds". And so on, later in text. Can be search&replaced... maybe.

**Comment by unixdigest** [comment]
Thanks! But "Fields", "class variables", and "attributes" are more-or-less the same.

Please see: http://stackoverflow.com/questions/16751269/oop-terminology-class-attribute-property-field-data-member/16751300#16751300
