### ISSUE TITLE
Remove "Essential PHP security" from recommended reading section

### ISSUE THREAD

**Issue by timoh6** [binarygenius/phpthewrongway#4]
While this book offers some good basic information, it leaves way too much unsaid (which is in part understandable as the book is 10+ years old) and in addition, it also gives some bad advice.

For example, see the crypto section or password handling or randomness generation. That's something we must know better today.

I don't have a direct substitute link, but http://phpsecurity.readthedocs.io/en/latest/ is worth to consider.

**Comment by unixdigest** [comment]
Thank you! The book has been removed and the link you provided added. I think also most of it is covered pretty well by OWASP.
