### ISSUE TITLE
Accessibility Check Results

### ISSUE THREAD

**Issue by umutphp** [binarygenius/phpthewrongway#64]
Hi,

I have checked the [site](http://www.phpthewrongway.com/) by using [pa11y](https://github.com/pa11y/pa11y) with WCAG2AA standard and the list of errors is attached in JSON format. The site has 29 errors but luckily there are only 2 types of errors. 

The result file is [phpthewrongway_errors.txt](https://github.com/unixsheikh/phpthewrongway/files/2857599/phpthewrongway_errors.txt).

**Comment by unixdigest** [comment]
Hi,

I'm sorry for the extremely late reply.

I think we can overlook the WCAG2AA errors for now.

**Comment by umutphp** [comment]
No worries :)
