### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by codeguy** [binarygenius/phpthewrongway#9]
Hi! Just read through this. I saw the title and was half-expecting a cynical humor piece, but I actually agree with a lot of your points. It seems fairly obvious that this is targeted at my own work given the site title and your disdain for the term "Modern PHP". But I don't see why... I agree with a lot of your points, and I don't think I've ever espoused any of the "wrong ways" that you describe on your site.

Anyway, I honestly and truly welcome your pull requests to "PHP The Right Way". I think you could make some great additions to that site.

**Comment by lianglee** [comment]
**....But I don't see why... I agree with a lot of your points,....**
Because you are real programmer unlike others who just keeping saying stuff without actually knowing it.

**Comment by unixdigest** [comment]
@codeguy Hi!

Thank you for your comment.

"PHP The Right Way" was taken so "PHP The Wrong Way" was the obvious choice :)

This website isn't targeted specifically at your work.

Thank you very much for your invite to participate. Also feel free to use whatever you find useful.
